### ISSUE TITLE
Ser etter å skrive kode for ffi

### ISSUE THREAD

**Issue by evenstensberg** [FFI-no/Paper-radar-signature-matching#1]
Hei. Jeg ser etter noen java/typescript prosjeker å bidra til, men ser ikke ut til at FFI har noen prosjekter åpne for øyeblikket. Er det noen måte å hjelpe til på? Jeg er god i JS/TS, og helst sånne typer prosjekter.

**Comment by martstr** [comment]
Hei! Kode som publiseres på FFIs Github-konto er for det meste kode som støtter publikasjoner, altså for å demonstrere funksjonalitet. Du står fritt til å klone dette og jobbe videre med det, men jeg kjenner ikke til noen prosjekter som er forsøkt crowdsourced.
